In [62]:
import pandas as pd
import numpy as np

In [63]:
df = pd.read_csv('datasets/q2_data.csv')

In [64]:
df

        age  income student credit_rating buys_computer
0      <=30    high      no          fair            no
1      <=30    high      no     excellent            no
2   31...40    high      no          fair           yes
3       >40  medium      no          fair           yes
4       >40     low     yes          fair           yes
5       >40     low     yes     excellent            no
6   31...40     low     yes     excellent           yes
7      <=30  medium      no          fair            no
8      <=30     low     yes          fair           yes
9       >40  medium     yes          fair           yes
10     <=30  medium     yes     excellent           yes
11  31...40  medium      no     excellent           yes
12  31...40    high     yes          fair           yes
13      >40  medium      no     excellent            no

In [74]:
def Naive_Bayes(df, pred_col:str, A:str, B):
    prior_probability = 1
    evidence = 1
    for feature in B:
        total_count = df[feature].count()
        count = ((df[pred_col] == A) & (df[feature] == B[feature])).astype(int).sum()
        prior_probability *= float(count) / (df[pred_col] == A).astype(int).sum()
        evidence *= float((df[feature] == B[feature]).astype(int).sum()) / total_count
    
    likelihood = float((df[pred_col] == A).astype(int).sum()) / df[pred_col].count()

    return (prior_probability * likelihood)/evidence

In [79]:
B = {
    'age': '<=30',
    'income': 'medium',
    'student': 'yes',
    'credit_rating': 'fair'
}
pred_col = 'buys_computer'
probs = {}
for A in df[pred_col]:
    probs[A] = Naive_Bayes(df, 'buys_computer', A, B)

print(f'Prediction for given conditions is {max(probs)}')

Prediction for given conditions is yes